---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-15.04
  - name: debian76
    driver:
      box: chef/debian-7.6
      box_url: chef/debian-7.6
  - name: centos510
    driver:
      box: chef/centos-5.10
      box_url: chef/centos-5.10
  - name: centos65
    driver:
      box: chef/centos-6.5
      box_url: chef/centos-6.5


suites:
  - name: default
    run_list:
      - recipe[linux-tweak::default]
    attributes:
  - name: bashoverride
    run_list:
      - recipe[linux-tweak::default]
    attributes:
      linux-tweak:
        PS1: 'export PS1="\[\033[38;5;0m\](\[$(tput sgr0)\]\[\033[38;5;15m\]\u\[$(tput sgr0)\]\[\033[38;5;0m\]@\[$(tput sgr0)\]\[\033[38;5;15m\]\h-\[$(tput sgr0)\]\[\033[38;5;0m\])(\[$(tput sgr0)\]\[\033[38;5;15m\]\t\[$(tput sgr0)\]\[\033[38;5;0m\])\[$(tput sgr0)\]\[\033[38;5;15m\]-\[$(tput sgr0)\]\[\033[38;5;0m\](\[$(tput sgr0)\]\[\033[38;5;12m\]\w\[$(tput sgr0)\]\[\033[38;5;0m\])\[$(tput sgr0)\]\[\033[38;5;15m\]\n\[$(tput sgr0)\]\[\033[38;5;0m\]>\[$(tput sgr0)\]"'