name             'linux-tweak'
maintainer       'Matthew Ahrenstein'
maintainer_email '@ahrenstein'
license          'See LICENSE.txt'
description      'Performs various tweaks on fresh Linux installs'
long_description 'Removes Landscape garbage from Ubuntu systems, tweaks system-wide bashrc settings'
version          '0.2.0'
depends          'line', '0.6.1'
